In [32]:
import pyalex
from pyalex import Works, Authors, Sources, Institutions, Topics, Publishers, Funders
import pandas as pd
import pickle

In [14]:
metadata_df = pd.read_json("../data/metadata_rich_df.json")

In [40]:
metadata_df.head(5)

,creator,datePublished,docType,doi,id,identifier,isPartOf,issueNumber,keyphrase,language,...,volumeNumber,wordCount,id_kase,docSubType,sourceCategory,abstract,subTitle,year,decade,bidecade
0,[Gerald F. Moede],1974-04-01,article,10.1111/j.1758-6623.1974.tb02427.x,ark://27927/phx7f872pd,"[{'name': 'doi', 'value': '10.1111/j.1758-6623...",The Ecumenical Review,2,"[church, church union, christian unity, confes...",[eng],...,26,7827,0,None,None,None,None,1974,1970,1960-1979
1,[Ben C. Ollenburger],1987-10-01,article,10.1177/004057368704400307,ark://27927/phx6238nb98,"[{'name': 'doi', 'value': '10.1177/00405736870...",Theology Today,3,"[haarlem, miep gies, german, suffering, hollan...",[eng],...,44,5181,1,None,None,None,None,1987,1980,1980-1999
2,[Eric L. Johnson],1997-03-01,article,10.1177/009164719702500102,ark://27927/phz2f6c9d3v,"[{'name': 'doi', 'value': '10.1177/00916471970...",Journal of Psychology and Theology,1,"[kingdom, christian, creation, lordship, knowl...",[eng],...,25,13697,2,None,None,None,None,1997,1990,1980-1999
3,"[Kimberly Matheson, Hymie Anisman, Renate Ysse...",2010-02-01,article,10.1177/1088868309349693,ark://27927/pgfvbkcxrg,"[{'name': 'doi', 'value': '10.1177/10888683093...",Personality and Social Psychology Review,1,"[religious, identity, religious identity, soci...",[eng],...,14,9915,3,None,None,None,None,2010,2010,2000-2019
4,[David J. Clark],1975-01-01,article,10.1177/026009357502600107,ark://27927/phx5181bbsv,"[{'name': 'doi', 'value': '10.1177/02600935750...",The Bible Translator (1950-2012),1,"[haenchen, overboard, barclay, apostles, went ...",[eng],...,26,1652,4,None,None,None,None,1975,1970,1960-1979

In [15]:
metadata_df[metadata_df["doi"].notnull()]

np.int64(13100)

In [2]:
pyalex.config.email = "kase@ff.zcu.cz"

In [4]:
pyalex.config.max_retries = 100000
pyalex.config.retry_backoff_factor = 0.1
pyalex.config.retry_http_codes = [429, 500, 503]

In [46]:
doi_base = "https://doi.org/"
doi = doi_base + "10.1177/1088868309349693"
doi
w = Works()[doi]
w

{'id': 'https://openalex.org/W2016703919',
 'doi': 'https://doi.org/10.1177/1088868309349693',
 'title': 'Religiosity as Identity: Toward an Understanding of Religion From a Social Identity Perspective',
 'display_name': 'Religiosity as Identity: Toward an Understanding of Religion From a Social Identity Perspective',
 'publication_year': 2010,
 'publication_date': '2010-01-19',
 'ids': {'openalex': 'https://openalex.org/W2016703919',
  'doi': 'https://doi.org/10.1177/1088868309349693',
  'mag': '2016703919',
  'pmid': 'https://pubmed.ncbi.nlm.nih.gov/20089847'},
 'language': 'en',
 'primary_location': {'is_oa': False,
  'landing_page_url': 'https://doi.org/10.1177/1088868309349693',
  'pdf_url': None,
  'source': {'id': 'https://openalex.org/S37739784',
   'display_name': 'Personality and Social Psychology Review',
   'issn_l': '1532-7957',
   'issn': ['1532-7957', '1088-8683'],
   'is_oa': False,
   'is_in_doaj': False,
   'is_indexed_in_scopus': True,
   'is_core': True,
   'host_organization': 'https://openalex.org/P4310320017',
   'host_organization_name': 'SAGE Publishing',
   'host_organization_lineage': ['https://openalex.org/P4310320017'],
   'host_organization_lineage_names': ['SAGE Publishing'],
   'type': 'journal'},
  'license': None,
  'license_id': None,
  'version': None,
  'is_accepted': False,
  'is_published': False},
 'type': 'article',
 'type_crossref': 'journal-article',
 'indexed_in': ['crossref', 'pubmed'],
 'open_access': {'is_oa': False,
  'oa_status': 'closed',
  'oa_url': None,
  'any_repository_has_fulltext': False},
 'authorships': [{'author_position': 'first',
   'author': {'id': 'https://openalex.org/A5003590133',
    'display_name': 'Renate Ysseldyk',
    'orcid': 'https://orcid.org/0000-0002-1411-2017'},
   'institutions': [{'id': 'https://openalex.org/I67031392',
     'display_name': 'Carleton University',
     'ror': 'https://ror.org/02qtvee93',
     'country_code': 'CA',
     'type': 'funder',
     'lineage': ['https://openalex.org/I67031392']}],
   'countries': ['CA'],
   'is_corresponding': False,
   'raw_author_name': 'Renate Ysseldyk',
   'raw_affiliation_strings': ['Carleton University, Ottawa, Ontario, Canada,'],
   'affiliations': [{'raw_affiliation_string': 'Carleton University, Ottawa, Ontario, Canada,',
     'institution_ids': ['https://openalex.org/I67031392']}]},
  {'author_position': 'middle',
   'author': {'id': 'https://openalex.org/A5037330792',
    'display_name': 'Kimberly Matheson',
    'orcid': 'https://orcid.org/0000-0003-1150-3335'},
   'institutions': [{'id': 'https://openalex.org/I67031392',
     'display_name': 'Carleton University',
     'ror': 'https://ror.org/02qtvee93',
     'country_code': 'CA',
     'type': 'funder',
     'lineage': ['https://openalex.org/I67031392']}],
   'countries': ['CA'],
   'is_corresponding': False,
   'raw_author_name': 'Kimberly Matheson',
   'raw_affiliation_strings': ['Carleton University, Ottawa, Ontario, Canada'],
   'affiliations': [{'raw_affiliation_string': 'Carleton University, Ottawa, Ontario, Canada',
     'institution_ids': ['https://openalex.org/I67031392']}]},
  {'author_position': 'last',
   'author': {'id': 'https://openalex.org/A5110122665',
    'display_name': 'Hymie Anisman',
    'orcid': None},
   'institutions': [{'id': 'https://openalex.org/I67031392',
     'display_name': 'Carleton University',
     'ror': 'https://ror.org/02qtvee93',
     'country_code': 'CA',
     'type': 'funder',
     'lineage': ['https://openalex.org/I67031392']}],
   'countries': ['CA'],
   'is_corresponding': False,
   'raw_author_name': 'Hymie Anisman',
   'raw_affiliation_strings': ['Carleton University, Ottawa, Ontario, Canada'],
   'affiliations': [{'raw_affiliation_string': 'Carleton University, Ottawa, Ontario, Canada',
     'institution_ids': ['https://openalex.org/I67031392']}]}],
 'institution_assertions': [],
 'countries_distinct_count': 1,
 'institutions_distinct_count': 1,
 'corresponding_author_ids': [],
 'corresponding_institution_ids': [],
 'apc_list': None,
 'apc_paid': None,
 'fwci': 27.712,
 'has_fulltext': True,
 'fulltext_origin': 'ngrams',
 'cited_by_count': 732,
 'citation_normalized_percentile': {'value': 0.999793,
  'is_in_top_1_percent': True,
  'is_in_top_10_percent': True},
 'cited_by_percentile_year': {'min': 99, 'max': 100},
 'biblio': {'volume': '14',
  'issue': '1',
  'first_page': '60',
  'last_page': '71'},
 'is_retracted': False,
 'is_paratext': False,
 'primary_topic': {'id': 'https://openalex.org/T10509',
  'display_name': 'Religion, Spirituality, and Psychology',
  'score': 0.9996,
  'subfield': {'id': 'https://openalex.org/subfields/3306',
   'display_name': 'Health'},
  'field': {'id': 'https://openalex.org/fields/33',
   'display_name': 'Social Sciences'},
  'domain': {'id': 'https://openalex.org/domains/2',
   'display_name': 'Social Sciences'}},
 'topics': [{'id': 'https://openalex.org/T10509',
   'display_name': 'Religion, Spirituality, and Psychology',
   'score': 0.9996,
   'subfield': {'id': 'https://openalex.org/subfields/3306',
    'display_name': 'Health'},
   'field': {'id': 'https://openalex.org/fields/33',
    'display_name': 'Social Sciences'},
   'domain': {'id': 'https://openalex.org/domains/2',
    'display_name': 'Social Sciences'}},
  {'id': 'https://openalex.org/T11507',
   'display_name': 'Religion and Society Interactions',
   'score': 0.9994,
   'subfield': {'id': 'https://openalex.org/subfields/3312',
    'display_name': 'Sociology and Political Science'},
   'field': {'id': 'https://openalex.org/fields/33',
    'display_name': 'Social Sciences'},
   'domain': {'id': 'https://openalex.org/domains/2',
    'display_name': 'Social Sciences'}},
  {'id': 'https://openalex.org/T11454',
   'display_name': 'Cultural Differences and Values',
   'score': 0.9959,
   'subfield': {'id': 'https://openalex.org/subfields/3207',
    'display_name': 'Social Psychology'},
   'field': {'id': 'https://openalex.org/fields/32',
    'display_name': 'Psychology'},
   'domain': {'id': 'https://openalex.org/domains/2',
    'display_name': 'Social Sciences'}}],
 'keywords': [{'id': 'https://openalex.org/keywords/religious-identity',
   'display_name': 'Religious Identity',
   'score': 0.6280031},
  {'id': 'https://openalex.org/keywords/social-identity-approach',
   'display_name': 'Social identity approach',
   'score': 0.56163585},
  {'id': 'https://openalex.org/keywords/identity-formation',
   'display_name': 'Identity Formation',
   'score': 0.5358679},
  {'id': 'https://openalex.org/keywords/atheism',
   'display_name': 'Atheism',
   'score': 0.49247226},
  {'id': 'https://openalex.org/keywords/fundamentalism',
   'display_name': 'Fundamentalism',
   'score': 0.4108655}],
 'concepts': [{'id': 'https://openalex.org/C2779793952',
   'wikidata': 'https://www.wikidata.org/wiki/Q1553701',
   'display_name': 'Religiosity',
   'level': 2,
   'score': 0.7928055},
  {'id': 'https://openalex.org/C77805123',
   'wikidata': 'https://www.wikidata.org/wiki/Q161272',
   'display_name': 'Social psychology',
   'level': 1,
   'score': 0.6648294},
  {'id': 'https://openalex.org/C98447023',
   'wikidata': 'https://www.wikidata.org/wiki/Q1540351',
   'display_name': 'Social identity theory',
   'level': 3,
   'score': 0.6511352},
  {'id': 'https://openalex.org/C50718005',
   'wikidata': 'https://www.wikidata.org/wiki/Q4392985',
   'display_name': 'Religious identity',
   'level': 3,
   'score': 0.6280031},
  {'id': 'https://openalex.org/C195755200',
   'wikidata': 'https://www.wikidata.org/wiki/Q7551162',
   'display_name': 'Social identity approach',
   'level': 4,
   'score': 0.56163585},
  {'id': 'https://openalex.org/C2778355321',
   'wikidata': 'https://www.wikidata.org/wiki/Q17079427',
   'display_name': 'Identity (music)',
   'level': 2,
   'score': 0.53766656},
  {'id': 'https://openalex.org/C97343919',
   'wikidata': 'https://www.wikidata.org/wiki/Q1095779',
   'display_name': 'Identity formation',
   'level': 3,
   'score': 0.5358679},
  {'id': 'https://openalex.org/C15744967',
   'wikidata': 'https://www.wikidata.org/wiki/Q9418',
   'display_name': 'Psychology',
   'level': 0,
   'score': 0.5304296},
  {'id': 'https://openalex.org/C180872759',
   'wikidata': 'https://www.wikidata.org/wiki/Q874405',
   'display_name': 'Social group',
   'level': 2,
   'score': 0.50976247},
  {'id': 'https://openalex.org/C2779783995',
   'wikidata': 'https://www.wikidata.org/wiki/Q7066',
   'display_name': 'Atheism',
   'level': 2,
   'score': 0.49247226},
  {'id': 'https://openalex.org/C2780789983',
   'wikidata': 'https://www.wikidata.org/wiki/Q9149',
   'display_name': 'Fundamentalism',
   'level': 3,
   'score': 0.4108655},
  {'id': 'https://openalex.org/C144024400',
   'wikidata': 'https://www.wikidata.org/wiki/Q21201',
   'display_name': 'Sociology',
   'level': 0,
   'score': 0.39836508},
  {'id': 'https://openalex.org/C111472728',
   'wikidata': 'https://www.wikidata.org/wiki/Q9471',
   'display_name': 'Epistemology',
   'level': 1,
   'score': 0.38236576},
  {'id': 'https://openalex.org/C2777410049',
   'wikidata': 'https://www.wikidata.org/wiki/Q1860557',
   'display_name': 'Self-concept',
   'level': 2,
   'score': 0.17171249},
  {'id': 'https://openalex.org/C199539241',
   'wikidata': 'https://www.wikidata.org/wiki/Q7748',
   'display_name': 'Law',
   'level': 1,
   'score': 0.10761568},
  {'id': 'https://openalex.org/C94625758',
   'wikidata': 'https://www.wikidata.org/wiki/Q7163',
   'display_name': 'Politics',
   'level': 2,
   'score': 0.09749681},
  {'id': 'https://openalex.org/C17744445',
   'wikidata': 'https://www.wikidata.org/wiki/Q36442',
   'display_name': 'Political science',
   'level': 0,
   'score': 0.09200376},
  {'id': 'https://openalex.org/C107038049',
   'wikidata': 'https://www.wikidata.org/wiki/Q35986',
   'display_name': 'Aesthetics',
   'level': 1,
   'score': 0.08957851},
  {'id': 'https://openalex.org/C138885662',
   'wikidata': 'https://www.wikidata.org/wiki/Q5891',
   'display_name': 'Philosophy',
   'level': 0,
   'score': 0.08106956}],
 'mesh': [{'descriptor_ui': 'D012069',
   'descriptor_name': 'Religion and Psychology',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': True},
  {'descriptor_ui': 'D012933',
   'descriptor_name': 'Social Identification',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': True},
  {'descriptor_ui': 'D000223',
   'descriptor_name': 'Adaptation, Psychological',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': False},
  {'descriptor_ui': 'D003220',
   'descriptor_name': 'Conflict, Psychological',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': False},
  {'descriptor_ui': 'D003469',
   'descriptor_name': 'Culture',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': False},
  {'descriptor_ui': 'D006801',
   'descriptor_name': 'Humans',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': False},
  {'descriptor_ui': 'D009042',
   'descriptor_name': 'Motivation',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': False},
  {'descriptor_ui': 'D011287',
   'descriptor_name': 'Prejudice',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': False},
  {'descriptor_ui': 'D011788',
   'descriptor_name': 'Quality of Life',
   'qualifier_ui': 'Q000523',
   'qualifier_name': 'psychology',
   'is_major_topic': False},
  {'descriptor_ui': 'D011788',
   'descriptor_name': 'Quality of Life',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': False},
  {'descriptor_ui': 'D013561',
   'descriptor_name': 'Symbolism',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': False},
  {'descriptor_ui': 'D014754',
   'descriptor_name': 'Violence',
   'qualifier_ui': 'Q000523',
   'qualifier_name': 'psychology',
   'is_major_topic': False},
  {'descriptor_ui': 'D014754',
   'descriptor_name': 'Violence',
   'qualifier_ui': '',
   'qualifier_name': None,
   'is_major_topic': False}],
 'locations_count': 2,
 'locations': [{'is_oa': False,
   'landing_page_url': 'https://doi.org/10.1177/1088868309349693',
   'pdf_url': None,
   'source': {'id': 'https://openalex.org/S37739784',
    'display_name': 'Personality and Social Psychology Review',
    'issn_l': '1532-7957',
    'issn': ['1532-7957', '1088-8683'],
    'is_oa': False,
    'is_in_doaj': False,
    'is_indexed_in_scopus': True,
    'is_core': True,
    'host_organization': 'https://openalex.org/P4310320017',
    'host_organization_name': 'SAGE Publishing',
    'host_organization_lineage': ['https://openalex.org/P4310320017'],
    'host_organization_lineage_names': ['SAGE Publishing'],
    'type': 'journal'},
   'license': None,
   'license_id': None,
   'version': None,
   'is_accepted': False,
   'is_published': False},
  {'is_oa': False,
   'landing_page_url': 'https://pubmed.ncbi.nlm.nih.gov/20089847',
   'pdf_url': None,
   'source': {'id': 'https://openalex.org/S4306525036',
    'display_name': 'PubMed',
    'issn_l': None,
    'issn': None,
    'is_oa': False,
    'is_in_doaj': False,
    'is_indexed_in_scopus': False,
    'is_core': False,
    'host_organization': 'https://openalex.org/I1299303238',
    'host_organization_name': 'National Institutes of Health',
    'host_organization_lineage': ['https://openalex.org/I1299303238'],
    'host_organization_lineage_names': ['National Institutes of Health'],
    'type': 'repository'},
   'license': None,
   'license_id': None,
   'version': None,
   'is_accepted': False,
   'is_published': False}],
 'best_oa_location': None,
 'sustainable_development_goals': [{'id': 'https://metadata.un.org/sdg/10',
   'score': 0.67,
   'display_name': 'Reduced inequalities'}],
 'grants': [],
 'datasets': [],
 'versions': [],
 'referenced_works_count': 114,
 'referenced_works': ['https://openalex.org/W1549268360',
  'https://openalex.org/W1590776345',
  'https://openalex.org/W1598549676',
  'https://openalex.org/W1965210455',
  'https://openalex.org/W1966643208',
  'https://openalex.org/W1967099079',
  'https://openalex.org/W1969474693',
  'https://openalex.org/W1969892598',
  'https://openalex.org/W1974863197',
  'https://openalex.org/W1978493498',
  'https://openalex.org/W1980942241',
  'https://openalex.org/W1986357892',
  'https://openalex.org/W1990102209',
  'https://openalex.org/W1994163646',
  'https://openalex.org/W2004249091',
  'https://openalex.org/W2005640289',
  'https://openalex.org/W2013021485',
  'https://openalex.org/W2017151217',
  'https://openalex.org/W2017309688',
  'https://openalex.org/W2021082932',
  'https://openalex.org/W2022598112',
  'https://openalex.org/W2030248402',
  'https://openalex.org/W2031471454',
  'https://openalex.org/W2033585341',
  'https://openalex.org/W2035183364',
  'https://openalex.org/W2041313762',
  'https://openalex.org/W2041655523',
  'https://openalex.org/W2041949427',
  'https://openalex.org/W2043719293',
  'https://openalex.org/W2047180961',
  'https://openalex.org/W2049298007',
  'https://openalex.org/W2054455595',
  'https://openalex.org/W2057418027',
  'https://openalex.org/W2059036015',
  'https://openalex.org/W2062907051',
  'https://openalex.org/W2064857070',
  'https://openalex.org/W2067123626',
  'https://openalex.org/W2067421031',
  'https://openalex.org/W2069412933',
  'https://openalex.org/W2069816762',
  'https://openalex.org/W2071901262',
  'https://openalex.org/W2072253009',
  'https://openalex.org/W2075255203',
  'https://openalex.org/W2075532150',
  'https://openalex.org/W2076304740',
  'https://openalex.org/W2076978897',
  'https://openalex.org/W2077588541',
  'https://openalex.org/W2077727618',
  'https://openalex.org/W2078848640',
  'https://openalex.org/W2080818334',
  'https://openalex.org/W2081105313',
  'https://openalex.org/W2081155210',
  'https://openalex.org/W2085453342',
  'https://openalex.org/W2085610800',
  'https://openalex.org/W2087429638',
  'https://openalex.org/W2089318233',
  'https://openalex.org/W2091447799',
  'https://openalex.org/W2093211145',
  'https://openalex.org/W2093761598',
  'https://openalex.org/W2097810903',
  'https://openalex.org/W2098038440',
  'https://openalex.org/W2102756860',
  'https://openalex.org/W2102896733',
  'https://openalex.org/W2105354632',
  'https://openalex.org/W2106207705',
  'https://openalex.org/W2108741493',
  'https://openalex.org/W2110723717',
  'https://openalex.org/W2110908878',
  'https://openalex.org/W2111040314',
  'https://openalex.org/W2111449565',
  'https://openalex.org/W2113065292',
  'https://openalex.org/W2114820294',
  'https://openalex.org/W2115577372',
  'https://openalex.org/W2118723788',
  'https://openalex.org/W2124919907',
  'https://openalex.org/W2126127668',
  'https://openalex.org/W2128539234',
  'https://openalex.org/W2140173604',
  'https://openalex.org/W2143135888',
  'https://openalex.org/W2150816559',
  'https://openalex.org/W2151905283',
  'https://openalex.org/W2159850840',
  'https://openalex.org/W2160004079',
  'https://openalex.org/W2162040794',
  'https://openalex.org/W2163138441',
  'https://openalex.org/W2166450253',
  'https://openalex.org/W2169671134',
  'https://openalex.org/W2187019535',
  'https://openalex.org/W230927011',
  'https://openalex.org/W2409168984',
  'https://openalex.org/W2438901335',
  'https://openalex.org/W2489511923',
  'https://openalex.org/W2497838971',
  'https://openalex.org/W2897464304',
  'https://openalex.org/W2940400818',
  'https://openalex.org/W2940507356',
  'https://openalex.org/W3130633277',
  'https://openalex.org/W313134013',
  'https://openalex.org/W3187436700',
  'https://openalex.org/W4205511911',
  'https://openalex.org/W4231406674',
  'https://openalex.org/W4233306663',
  'https://openalex.org/W4234905672',
  'https://openalex.org/W4241362814',
  'https://openalex.org/W4252778039',
  'https://openalex.org/W4292542163',
  'https://openalex.org/W4297688511',
  'https://openalex.org/W4401256524',
  'https://openalex.org/W562578050',
  'https://openalex.org/W620683739',
  'https://openalex.org/W625769710',
  'https://openalex.org/W644944753',
  'https://openalex.org/W659370500',
  'https://openalex.org/W90970949'],
 'related_works': ['https://openalex.org/W4379597254',
  'https://openalex.org/W4319233909',
  'https://openalex.org/W3161395118',
  'https://openalex.org/W3160122845',
  'https://openalex.org/W2966900281',
  'https://openalex.org/W2925331481',
  'https://openalex.org/W2907325404',
  'https://openalex.org/W2890819242',
  'https://openalex.org/W2606455105',
  'https://openalex.org/W1002685784'],
 'abstract_inverted_index': {'As': [0],
  'a': [1, 6, 17, 30, 68, 74, 86, 132, 136],
  'social': [2, 25, 43, 70, 133],
  'identity': [3, 85, 104, 134],
  'anchored': [4],
  'in': [5, 21, 73, 146],
  'system': [7, 76, 138],
  'of': [8, 67, 92, 118, 127, 143],
  'guiding': [9],
  'beliefs': [10],
  'and': [11, 24, 34, 57, 80, 135, 151],
  'symbols,': [12],
  'religion': [13],
  'ought': [14],
  'to': [15, 124],
  'serve': [16],
  'uniquely': [18],
  'powerful': [19],
  'function': [20, 130],
  'shaping': [22],
  'psychological': [23],
  'processes.': [26],
  'Religious': [27],
  'identification': [28, 40],
  'offers': [29, 78],
  'distinctive': [31],
  '“sacred”': [32],
  'worldview': [33],
  '“eternal”': [35],
  'group': [36, 62],
  'membership,': [37],
  'unmatched': [38],
  'by': [39, 53, 115],
  'with': [41],
  'other': [42],
  'groups.': [44, 152],
  'Thus,': [45],
  'religiosity': [46],
  'might': [47],
  'be': [48],
  'explained,': [49],
  'at': [50],
  'least': [51],
  'partially,': [52],
  'the': [54, 90, 144],
  'marked': [55],
  'cognitive': [56],
  'emotional': [58],
  'value': [59],
  'that': [60, 77, 95],
  'religious': [61, 84, 103, 122],
  'membership': [63],
  'provides.': [64],
  'The': [65],
  'uniqueness': [66, 96],
  'positive': [69],
  'group,': [71],
  'grounded': [72],
  'belief': [75, 137],
  'epistemological': [79],
  'ontological': [81],
  'certainty,': [82],

In [25]:
def get_openalex_data(rawdoi):
    try:
        doi = doi_base + rawdoi
        w = Works()[doi]
        return w
    except:
        return None

In [30]:
%%time
works_series = metadata_df["doi"].apply(get_openalex_data)

CPU times: user 1min 26s, sys: 7.04 s, total: 1min 33s
Wall time: 1h 28min 23s

In [31]:
len(works_series)

25000

In [33]:
with open("../data/openalex_works_series.pkl", "wb") as f:
    works_series.to_pickle(f)
#works_series

In [59]:
def get_openalex_data_from_series(dataentry, attr1, attr2=None, attr3=None):
    try:
        if attr3:
            attr_value = dataentry[attr1][attr2][attr3]
        else:
            if attr2:
                attr_value = dataentry[attr1][attr2]
            else:
                attr_value = dataentry[attr1]
    except:
        attr_value = None
    return attr_value

In [71]:
w

'As a social identity anchored in a system of guiding beliefs and symbols, religion ought to serve a uniquely powerful function in shaping psychological and social processes. Religious identification offers a distinctive “sacred” worldview and “eternal” group membership, unmatched by identification with other social groups. Thus, religiosity might be explained, at least partially, by the marked cognitive and emotional value that religious group membership provides. The uniqueness of a positive social group, grounded in a belief system that offers epistemological and ontological certainty, lends religious identity a twofold advantage for the promotion of well-being. However, that uniqueness may have equally negative impacts when religious identity itself is threatened through intergroup conflict. Such consequences are illustrated by an examination of identities ranging from religious fundamentalism to atheism. Consideration of religion’s dual function as a social identity and a belief system may facilitate greater understanding of the variability in its importance across individuals and groups.'

In [74]:
metadata_df["oalex_id"] = works_series.apply(lambda x: get_openalex_data_from_series(x, "id"))
metadata_df["oalex_abstract"] = works_series.apply(lambda x: get_openalex_data_from_series(x, "abstract"))
metadata_df["oalex_source_id"] = works_series.apply(lambda x: get_openalex_data_from_series(x, "primary_location", "source", "id"))
metadata_df["oalex_source_org_id"] = works_series.apply(lambda x: get_openalex_data_from_series(x, "primary_location", "source", "host_organization_name"))

In [66]:
w
authors_countries = []
for authorentry in w["authorships"]:
    authors_countries.extend(authorentry["countries"])
authors_countries

['CA', 'CA', 'CA']

In [67]:
def get_authors_countries(dataentry):
    authors_countries = []
    try:
        for authorentry in dataentry["authorships"]:
            authors_countries.extend(authorentry["countries"])
    except:
        pass
    return authors_countries

In [68]:
metadata_df["authors_countries"] = works_series.apply(get_authors_countries)

In [75]:
metadata_df.head(5)

,creator,datePublished,docType,doi,id,identifier,isPartOf,issueNumber,keyphrase,language,...,abstract,subTitle,year,decade,bidecade,oalex_id,oalex_source_id,oalex_source_org_id,authors_countries,oalex_abstract
0,[Gerald F. Moede],1974-04-01,article,10.1111/j.1758-6623.1974.tb02427.x,ark://27927/phx7f872pd,"[{'name': 'doi', 'value': '10.1111/j.1758-6623...",The Ecumenical Review,2,"[church, church union, christian unity, confes...",[eng],...,None,None,1974,1970,1960-1979,https://openalex.org/W2011908274,https://openalex.org/S158964946,Wiley,[US],None
1,[Ben C. Ollenburger],1987-10-01,article,10.1177/004057368704400307,ark://27927/phx6238nb98,"[{'name': 'doi', 'value': '10.1177/00405736870...",Theology Today,3,"[haarlem, miep gies, german, suffering, hollan...",[eng],...,None,None,1987,1980,1980-1999,https://openalex.org/W2322662414,https://openalex.org/S43703656,SAGE Publishing,[],"“For in their own bodies, Christians live exis..."
2,[Eric L. Johnson],1997-03-01,article,10.1177/009164719702500102,ark://27927/phz2f6c9d3v,"[{'name': 'doi', 'value': '10.1177/00916471970...",Journal of Psychology and Theology,1,"[kingdom, christian, creation, lordship, knowl...",[eng],...,None,None,1997,1990,1980-1999,https://openalex.org/W2310479311,https://openalex.org/S1000263748,SAGE Publishing,[US],The lordship of Christ over all of a Christian...
3,"[Kimberly Matheson, Hymie Anisman, Renate Ysse...",2010-02-01,article,10.1177/1088868309349693,ark://27927/pgfvbkcxrg,"[{'name': 'doi', 'value': '10.1177/10888683093...",Personality and Social Psychology Review,1,"[religious, identity, religious identity, soci...",[eng],...,None,None,2010,2010,2000-2019,https://openalex.org/W2016703919,https://openalex.org/S37739784,SAGE Publishing,"[CA, CA, CA]",As a social identity anchored in a system of g...
4,[David J. Clark],1975-01-01,article,10.1177/026009357502600107,ark://27927/phx5181bbsv,"[{'name': 'doi', 'value': '10.1177/02600935750...",The Bible Translator (1950-2012),1,"[haenchen, overboard, barclay, apostles, went ...",[eng],...,None,None,1975,1970,1960-1979,https://openalex.org/W2573138642,https://openalex.org/S2764715567,SAGE Publishing,[],None

In [76]:
metadata_df["abstract"].notnull().sum()

np.int64(1569)

In [77]:
metadata_df["oalex_abstract"].notnull().sum()

np.int64(5049)

In [78]:
metadata_df.to_json("../data/metadata_rich_oalex.json")