In [1]:
import nltk
import pandas as pd
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

import numpy as np
import math
import sys

In [3]:
metadata_df = pd.read_json("../data/metadata_rich_df.json")
metadata_df = metadata_df[metadata_df["language"].apply(lambda x: str(x)=="['eng']")]

In [4]:
sourcepath = "../data/large_files/trigrams_lemmatized/"
with open(sourcepath + "trigrams_lemmata_id_0.txt".format(str(id)), "r") as f:
    trigrams_list = f.readlines()

In [5]:
[el.strip() for el in trigrams_list][:10]

['religious matter',
 'divine hope',
 'divine hope',
 'leave unresolved',
 'leave unresolved',
 'racial equality',
 'racial equality',
 'joint action',
 'joint action',
 'joint action']

# Load vocabulary

In [6]:
bidecades_vocabs_counts_df = pickle.load(open("../data/bidecades_vocabs_counts_df.pickle", "rb"))
bidecades_vocabs_counts_df.head(5)

,1900-1919,1920-1939,1940-1959,1960-1979,1980-1999,2000-2019,total
man,11344.0,8183.0,24295.0,39235.0,48711.0,102378.0,468292.0
new,10162.0,10049.0,23620.0,42209.0,98326.0,298804.0,966340.0
god,9952.0,7062.0,27985.0,48646.0,108667.0,381223.0,1167070.0
jesus,9416.0,4416.0,11590.0,22810.0,49506.0,223950.0,643376.0
paul,8239.0,6563.0,19017.0,34910.0,103422.0,302719.0,949740.0

In [7]:
vocabulary = dict([(el[1], el[0]) for el in enumerate(bidecades_vocabs_counts_df.index)])

# Load trigrams

In [8]:
bidecades_strs = sorted([el for el in list(set(metadata_df["bidecade"])) if el != None])
bidecades_strs

['1900-1919', '1920-1939', '1940-1959', '1960-1979', '1980-1999', '2000-2019']

In [9]:
bidecade = "1900-1919"
ids = metadata_df[metadata_df["bidecade"]==bidecade]["id_kase"]
len(ids)

755

In [10]:
with open("../data/large_files/bidecade_trigrams_{}.txt".format(bidecade), "r") as f:
    subcorpus_ngrams = f.readlines()

In [11]:
[el.strip() for el in subcorpus_ngrams[:10]]

['michigan ann arbor',
 'bonner university',
 'bonner university',
 'iowa iowa',
 'iowa iowa',
 'kansas lawrence',
 'elliott university',
 'elliott university',
 'kansas lawrence kansas',
 'northfield minnesota']

In [12]:
vectorizer = TfidfVectorizer(vocabulary=vocabulary, lowercase=False)
X = vectorizer.fit_transform(subcorpus_ngrams)

In [13]:
X.shape

(634163, 4686)

In [14]:
cooc = X.T * X

In [15]:
cooc.max()

6037.338554244274

In [16]:
cooc.todense().max()

6037.338554244274

In [17]:
cooc_norm_dict = {}
for bidecade in bidecades_strs:
    with open("../data/large_files/bidecade_trigrams_{}.txt".format(bidecade), "r") as f:
        subcorpus_ngrams = f.readlines()
    vectorizer = TfidfVectorizer(vocabulary=vocabulary, lowercase=False)
    X = vectorizer.fit_transform(subcorpus_ngrams)
    cooc = X.T * X
    cooc_norm_dict[bidecade] = cooc

In [18]:
pickle.dump(cooc_norm_dict, open("../data/cooc_dict.pickle", "wb"))

# Vectors for the last 30 years (by halfdecades)

In [19]:
cooc_norm_dict_2000 = {}
for date in range(1990,2020,5):
    ids = metadata_df[metadata_df["year"].between(date, date+4)]["id_kase"]
    subcorpus_ngrams = []
    for id in ids:
        with open("../data/large_files/trigrams_lemmatized/trigrams_lemmata_id_{}.txt".format(str(id)), "r") as f:
            subcorpus_ngrams.extend([el for el in f.readlines()])
    vectorizer = TfidfVectorizer(vocabulary=vocabulary, lowercase=False)
    X = vectorizer.fit_transform(subcorpus_ngrams)
    cooc = X.T * X
    cooc_norm_dict_2000[str(date)+"-"+str(date+4)] = cooc

In [20]:
pickle.dump(cooc_norm_dict_2000, open("../data/cooc_dict_2000.pickle", "wb"))

# Vectorization example

In [22]:
corpus = [("apostle paul be"), ("apostle paul be"), ("scholar write be"), ("scholar be article")]
vocabulary = list(set([w for doc in [doc.split() for doc in corpus] for w in doc]))
vectorizer_tfidf = TfidfVectorizer(vocabulary=vocabulary, lowercase=False)
doc_term_tfidf = vectorizer_tfidf.fit_transform(corpus)

vectorizer_count = CountVectorizer(vocabulary=vocabulary, lowercase=False)
doc_term_count = vectorizer_count.fit_transform(corpus)

corpus = [("apostle paul be"),
          ("apostle paul be"),
          ("scholar write be"),
          ("scholar be article")]

In [23]:
doc_term_matrix_count = pd.DataFrame(doc_term_count.todense(), columns=vocabulary, index=["doc1", "doc2", "doc3", "doc4"])
doc_term_matrix_count

      scholar  paul  be  apostle  write  article
doc1        0     1   1        1      0        0
doc2        0     1   1        1      0        0
doc3        1     0   1        0      1        0
doc4        1     0   1        0      0        1

In [24]:
doc_term_matrix_tfidf = pd.DataFrame(doc_term_tfidf.todense(), columns=vocabulary, index=["doc1", "doc2", "doc3", "doc4"])
doc_term_matrix_tfidf

       scholar      paul        be   apostle     write   article
doc1  0.000000  0.640434  0.423897  0.640434  0.000000  0.000000
doc2  0.000000  0.640434  0.423897  0.640434  0.000000  0.000000
doc3  0.572892  0.000000  0.379192  0.000000  0.726641  0.000000
doc4  0.572892  0.000000  0.379192  0.000000  0.000000  0.726641

In [25]:
# TfIdf of Paul in doc1:
TF = 1 # term frequency
N = 4 # number of documents
DF = 2 # document frequency
IDF = np.log((N + 1) / (DF + 1)) + 1
doc1_Paul_tfidf = TF * IDF

In [26]:
doc_term_matrix_tfidf.loc["doc1"]

scholar    0.000000
paul       0.640434
be         0.423897
apostle    0.640434
write      0.000000
article    0.000000
Name: doc1, dtype: float64

In [27]:
def tfidf(corpus, vocabulary):
    # Compute document frequency (df) for each term in the vocabulary
    df = {word: 0 for word in vocabulary}
    for doc in corpus:
        words = doc.split()
        for word in set(words):
            if word in vocabulary:
                df[word] += 1

    # Compute inverse document frequency (idf) for each term in the vocabulary
    idf = {}
    N = len(corpus)
    for word in vocabulary:
        idf[word] = np.log((N + 1) / (df[word] + 1)) + 1

    # Compute term frequency (tf) for each document
    tf = np.zeros((N, len(vocabulary)))
    for i, doc in enumerate(corpus):
        words = doc.split()
        for j, word in enumerate(vocabulary):
            tf[i, j] = words.count(word)

    # Compute tf-idf for each document-term pair
    tfidf_matrix = tf * np.array(list(idf.values()))
    tfidf_manually = pd.DataFrame(tfidf_matrix, columns=vocabulary, index=["doc1", "doc2", "doc3", "doc4"])
    return tfidf_manually

In [28]:
tfidf_manually = tfidf(corpus, vocabulary)
tfidf_manually

       scholar      paul   be   apostle     write   article
doc1  0.000000  1.510826  1.0  1.510826  0.000000  0.000000
doc2  0.000000  1.510826  1.0  1.510826  0.000000  0.000000
doc3  1.510826  0.000000  1.0  0.000000  1.916291  0.000000
doc4  1.510826  0.000000  1.0  0.000000  0.000000  1.916291

doc1_Paul_tfidf = 1.51
eucl_norm = sqrt((1.51^2)+(1.51^2)+(0.0^2)+(1.0^2)+(0.0^2)+(0.0^2)) = 2.36
doc1_Paul_tfidf_norm = 1.51 / 2.36 = 0.64

In [34]:
doc1_Paul_tfidf = 1.51
eucl_norm = np.sqrt((1.51 ** 2) + (1.51 ** 2) + (0.0 ** 2) + (1.0 ** 2) + (0.0 ** 2) + (0.0 ** 2))
doc1_Paul_tfidf_norm = 1.51 / 2.36 # = 0.64

In [35]:
def exponent_as_string(val):
    return "(" + str(np.round(val,2)) + "^2)"

In [36]:
"eucl_norm = sqrt(" + "+".join(tfidf_manually.loc["doc1"].apply(exponent_as_string).tolist()) + ")"

'eucl_norm = sqrt((0.0^2)+(1.51^2)+(1.0^2)+(1.51^2)+(0.0^2)+(0.0^2))'

In [37]:
pd.DataFrame(tfidf_manually.loc["doc1"].apply(exponent_as_string)).T

      scholar      paul       be   apostle    write  article
doc1  (0.0^2)  (1.51^2)  (1.0^2)  (1.51^2)  (0.0^2)  (0.0^2)

In [38]:
vector = tfidf_manually.loc["doc1"]
eucl_norm = np.sqrt(sum([el*el for el in vector]))
eucl_norm

2.359065096782153

In [39]:
# L2 normalization, also known as Euclidean normalization, is a technique used to scale the vector length to a unit length. In the case of the TF-IDF matrix, L2 normalization is applied to each row vector (corresponding to a document) of the matrix.

# The normalization process involves dividing each element of the row vector by the Euclidean norm of the vector. The Euclidean norm of a vector v is defined as the square root of the sum of the squares of its components.
def euclidean_normalization(vector, order=2):
    eucl_norm = np.sqrt(sum([el*el for el in vector])) # The Euclidean norm of a vector v is defined as the square root of the sum of the squares of its components.
    vector_norm = vector / eucl_norm
    return vector_norm

In [40]:
tfidf_manually.apply(euclidean_normalization, axis=1)

       scholar      paul        be   apostle     write   article
doc1  0.000000  0.640434  0.423897  0.640434  0.000000  0.000000
doc2  0.000000  0.640434  0.423897  0.640434  0.000000  0.000000
doc3  0.572892  0.000000  0.379192  0.000000  0.726641  0.000000
doc4  0.572892  0.000000  0.379192  0.000000  0.000000  0.726641

# document-term to term-term matrix

In [42]:
doc_term_tfidf.T

<6x4 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Column format>

In [43]:
cooc = pd.DataFrame((doc_term_tfidf.todense().T * doc_term_tfidf.todense()), columns=vocabulary, index=vocabulary)
cooc

          scholar      paul        be   apostle     write   article
scholar  0.656412  0.000000  0.434472  0.000000  0.416287  0.416287
paul     0.000000  0.820312  0.542956  0.820312  0.000000  0.000000
be       0.434472  0.542956  0.646950  0.542956  0.275536  0.275536
apostle  0.000000  0.820312  0.542956  0.820312  0.000000  0.000000
write    0.416287  0.000000  0.275536  0.000000  0.528008  0.000000
article  0.416287  0.000000  0.275536  0.000000  0.000000  0.528008

In [44]:
cooc.sort_values("paul", ascending=False)["paul"]

paul       0.820312
apostle    0.820312
be         0.542956
scholar    0.000000
write      0.000000
article    0.000000
Name: paul, dtype: float64